# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config

project_id = "hkxqpjdjlyvgceevahab"

[api]
enabled = true

[db]
major_version = 17

[auth]
enabled = true
