#!/usr/bin/env node
/**
 * product-skills init
 * Analyze workspace lightly, install Product-Skills files, print human-friendly status.
 * Does not rewrite application architecture or perform mass refactors.
 */
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, '..');

function parseArgs(argv) {
  const out = { target: process.cwd() };
  for (let i = 2; i < argv.length; i += 1) {
    if (argv[i] === '--target') out.target = path.resolve(argv[++i] || '');
    else if (argv[i] === 'init') continue;
    else if (!argv[i].startsWith('-') && out.target === process.cwd()) {
      // allow: product-skills init <path>
      out.target = path.resolve(argv[i]);
    }
  }
  return out;
}

function exists(p) {
  return fs.existsSync(p);
}

function detectProject(target) {
  const pkgPath = path.join(target, 'package.json');
  let pkg = null;
  if (exists(pkgPath)) {
    try {
      pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    } catch {
      pkg = null;
    }
  }
  const deps = { ...(pkg?.dependencies || {}), ...(pkg?.devDependencies || {}) };
  const hasReact = Boolean(deps.react || deps['react-dom']);
  const hasTs =
    exists(path.join(target, 'tsconfig.json')) || Boolean(deps.typescript) || Boolean(deps['@types/react']);
  const srcCandidates = ['src', 'app', 'apps', 'packages'].filter((d) => exists(path.join(target, d)));
  const fsdHints = ['shared', 'entities', 'features', 'pages', 'widgets', 'app'].filter((layer) =>
    srcCandidates.some((root) => exists(path.join(target, root, layer)) || exists(path.join(target, 'src', layer))),
  );
  const testing = ['vitest', 'jest', 'playwright', '@playwright/test', 'cypress'].filter((d) => deps[d]);
  const deployment = [
    exists(path.join(target, 'vercel.json')) && 'vercel',
    exists(path.join(target, 'Dockerfile')) && 'docker',
    exists(path.join(target, '.github', 'workflows')) && 'github-actions',
  ].filter(Boolean);

  let projectType = 'unknown';
  if (pkg && hasReact) projectType = 'react-application';
  else if (pkg) projectType = 'node-package';
  else if (exists(path.join(target, 'README.md'))) projectType = 'documentation-or-empty';

  const architecture =
    fsdHints.length >= 2 ? `Feature-Sliced Design hints (${fsdHints.join(', ')})` : 'not clearly FSD yet';

  const requiredSkills = [
    'product/project-analysis',
    'product/product-discovery',
    'product/product-definition',
    'product/ux-flow',
    'delivery/architecture-decision',
    'delivery/react-fsd-poc',
    'quality/verification',
    'delivery/developer-handoff',
  ];

  return {
    projectType,
    language: hasTs ? 'TypeScript likely' : pkg ? 'JavaScript / mixed' : 'unknown',
    framework: hasReact ? 'React' : 'not detected as React',
    architecture,
    folders: srcCandidates,
    testing: testing.length ? testing.join(', ') : 'not detected',
    deployment: deployment.length ? deployment.join(', ') : 'not detected',
    requiredSkills,
    risks: [
      !hasReact ? 'React not detected — delivery skills still expect React + TypeScript + FSD for POC work.' : null,
      architecture.includes('not clearly') ? 'FSD not clearly present — require architecture-decision before coding.' : null,
      'Do not rewrite existing architecture without explicit approval.',
    ].filter(Boolean),
  };
}

function writeAnalysis(target, report) {
  const dir = path.join(target, '.ai-review');
  fs.mkdirSync(dir, { recursive: true });
  const body = `# Project Analysis Report

Generated by \`product-skills init\`.

## Current state

- project type: ${report.projectType}
- technology: ${report.language}; ${report.framework}
- architecture: ${report.architecture}
- folders: ${report.folders.join(', ') || 'n/a'}
- testing: ${report.testing}
- deployment: ${report.deployment}

## Recommended workflow

- Start from Product problem -> definition -> UX -> React FSD POC -> validation -> handoff
- For existing apps: smallest change only (see workflows/existing-project-improvement.md)

## Required skills

${report.requiredSkills.map((s) => `- ${s}`).join('\n')}

## Potential risks

${report.risks.map((r) => `- ${r}`).join('\n')}
`;
  fs.writeFileSync(path.join(dir, 'project-analysis.md'), body);
}

function printHumanStatus(report) {
  console.log('Analyzing project...');
  console.log('');
  console.log('✓ Project type detected');
  console.log('✓ Existing architecture detected');
  console.log('✓ Required skills selected');
  console.log('✓ Rules installed');
  console.log('✓ Agent instructions configured');
  console.log('');
  console.log('Product-Skills ready');
  console.log('');
  console.log(`Project type: ${report.projectType}`);
  console.log(`Stack hint: ${report.language} / ${report.framework}`);
  console.log(`Architecture: ${report.architecture}`);
  console.log('Review: .ai-review/project-analysis.md');
  console.log('Next: open a new AI chat and describe your product problem.');
}

const { target } = parseArgs(process.argv);
if (!target || !exists(target)) {
  console.error('Target directory not found. Use: product-skills init --target <path>');
  process.exit(1);
}

const report = detectProject(target);
writeAnalysis(target, report);

const installScript = path.join(packageRoot, 'install', 'install.mjs');
const installArgs = [installScript, '--target', target];
const install = spawnSync(process.execPath, installArgs, {
  stdio: 'inherit',
  shell: false,
});
if (install.status !== 0) {
  console.error('Install step failed.');
  process.exit(install.status || 1);
}

// Ensure .ai-review starter files exist in target
const reviewSrc = path.join(packageRoot, '.ai-review');
const reviewDest = path.join(target, '.ai-review');
fs.mkdirSync(reviewDest, { recursive: true });
if (exists(reviewSrc)) {
  for (const name of fs.readdirSync(reviewSrc)) {
    const from = path.join(reviewSrc, name);
    const to = path.join(reviewDest, name);
    if (fs.statSync(from).isFile() && !exists(to)) fs.copyFileSync(from, to);
  }
}
writeAnalysis(target, report);
printHumanStatus(report);
